version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_io:~/io
      - ./n8n_workflows:~/workflows
    restart: no
    environment:
      - N8N_RUNNERS_ENABLED=true

volumes:
  n8n_data:
    driver: local
  n8n_io:
    driver: local
  n8n_workflows:
    driver: local

networks:
  default:
    driver: bridge
