version: "3.8"
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_io:/io
      - ./n8n_workflows:/workflows
    restart: no
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - GENERIC_TIMEZONE="Europe/Berlin"
      - TZ="Europe/Berlin"
#      - N8N_PAYLOAD_SIZE_MAX=268435456 #Increases payload limit to 256MB
#      - NODE_OPTIONS=--max_old_space_size=8192 #Increases memory limit to 8GB

volumes:
  n8n_data:
    driver: local
  n8n_io:
    driver: local
  n8n_workflows:
    driver: local

networks:
  default:
    driver: bridge
